name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verificar estructura de directorios
      run: |
        ls -la

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Ensure executable permissions
      run: |
        chmod -R 755 ./node_modules/.bin

    - name: Verify Jest installation
      run: |
        npx jest --version

    - name: Run tests
      run: |
        npm test
